//>>built
define("dexist/util/$","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/selector/_loader dojo/selector/_loader!default dojo/on dojo/aspect dojo/request dojo/ready dojo/query dojo/Deferred dojo/when dojo/store/Memory dojo/dom-geometry dojo/dom-construct dojo/dom-style dojo/dom-attr dojo/dom-class dojo/NodeList-data dojo/NodeList-manipulate dojo/NodeList-traverse".split(" "),function(A,f,q,L,B,t,C,D,E,g,F,l,M,r,u,h,G,v){function m(){return!0}function n(){return!1}var w=/\r?\n/g,H=/^(?:submit|button|image|reset|file)$/i,
I=/^(?:input|select|textarea|keygen)/i,J=/^(?:checkbox|radio)$/i,x={};q.forEach("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a){x["[object "+a+"]"]=a.toLowerCase()});var s={hidden:function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight},visible:function(a){return!s.hidden(a)}},y=g.NodeList._adaptWithCondition(function(a){return function(b,c,d){return 2==arguments.length?a["string"==typeof c?"get":"set"](b,c):a.set(b,c,d)}}(G),function(a){return 1==a.length&&"string"==
typeof a[0]}),k=A("$.NodeList",[g.NodeList],{ready:E,add:function(a){this.push(a);return this},data:function(a,b){if(this.length){var c=this[0],d;try{d=c instanceof HTMLElement}catch(e){d="object"===typeof c&&1===c.nodeType&&"object"===typeof c.style&&"object"===typeof c.ownerDocument}return!d?0==arguments.length?c:1<arguments.length?c[a]=b:c[a]:this.inherited(arguments)[0]}},find:function(a){return g(a,this[0])},each:function(){var a=Array.prototype.slice.call(arguments),b=a.shift();this.forEach(function(c){b.apply(c,
a)});return this},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;b<c;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(rclass," ").indexOf(a))return!0;return!1},is:function(a){return!0===this.every(function(b){var c=$.query(a,b);return c.length?c[0]===b:!1})},attr:function(a,b){var c=y.apply(this,arguments);return void 0===b?c.join(""):c},prop:function(a,b){y.apply(this,arguments);var c=[];c.length||this.each(function(){this[a]&&(void 0!==b&&(this[a]=b),c.push(this[a]))});
c.length||this.each(function(){var b=$(a,this);b.length&&(c=b[0])});return c.length?c[0]:null},css:function(a){var b=this.map(function(){return h.get(this,a)});return"string"==typeof a?b.join(""):b},currentStyle:function(a){return this.map(function(){return h.get(this,a)}).join()},click:function(a){return void 0===a?this.trigger.apply(this,[]):this.bind.apply(this,["click",a])},bind:function(){var a=arguments[0],b=arguments.length;0<=a.indexOf(".")&&(a=a.split(".").shift());var c=arguments[b-1],d=
function(a){a=new $.Event(a);return c(a)};this.forEach(function(b){var c=t(b,a,d);b==document||b==window?b["evt-"+a]=c:$(b).data("evt-"+a,c)});return this},unbind:function(a){this.forEach(function(b){var c,d="evt-"+a;b==document||b==window?(c=b[d],delete b[d]):(c=$(b).data(d),$(b).removeData(d));c&&c.remove()})},trigger:function(a){a=!a||"string"==typeof a?a:a.type?a.type:a;this.forEach(function(b){t.emit(b,a,{bubbles:!0,cancelable:!0})});return this},width:function(a){return a?("string"!=typeof a&&
(a+="px"),this.forEach(function(b){return h.set(b,"width",a)}),this):this.map(function(){return h.get(this,"width")}).join()},outerWidth:function(){return r.getMarginBox(this[0]).w},outerHeight:function(){return r.getMarginBox(this[0]).h},height:function(a){return a?("string"!=typeof a&&(a+="px"),this.forEach(function(b){return h.set(b,"height",a)}),this):this.map(function(){return h.get(this,"height")}).join()},offset:function(){var a=r.position(this[0]);return{left:a.x,top:a.y}},hide:function(){this.forEach(function(a){v.add(a,
"dijitHidden")})},show:function(){this.forEach(function(a){v.remove(a,"dijitHidden")})},offsetParent:function(){return this.map(function(){return this.offsetParent||document.body})},get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:[].slice.call(this)},serializeArray:function(){var a=this.prop("elements"),a=a?$.makeArray(a):this;return(new k(a)).filter(function(a){var c=a.type;return a.name&&!$(a).is(":disabled")&&I.test(a.nodeName)&&!H.test(c)&&(this.checked||!J.test(c))}).map(function(a){var c=
$(a).val();return null==c?null:$.isArray(c)?$.map(c,function(c){return{name:a.name,value:c.replace(w,"\r\n")}}):{name:a.name,value:c.replace(w,"\r\n")}}).get()}});f.extend(k,{_NodeListCtor:k});g=function(a,b){var c=function(c,d){if("string"==typeof d&&(d=dom.byId(d),!d))return new b([]);var p="string"==typeof c?a(c,d):c?c.end&&c.on?c:[c]:[];return p.end&&p.on?p:new b(p)};c.matches=a.match||function(a,b,d){return 0<c.filter([a],b,d).length};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return-1<
q.indexOf(a,b)})};if("function"!=typeof a){var d=a.search;a=function(a,b){return d(b||document,a)}}return c}(B,k);var z=/:(:?[^ ,:.]+)/g;$=f.mixin(function(a,b){if(0===arguments.length)return f.mixin(new k([]),$.fn);if("string"===typeof a){if("\x3c"===a[0]&&"\x3e"===a[a.length-1]&&3<=a.length){var c=u.toDom(a);b&&u.place(c,b);return f.mixin(g(c),$.fn)}if(a.match(z)&&(c=a.replace(z,"$1"),s[c]))return s[c](b)}return f.mixin(g.apply(this,arguments),$.fn)},dojo,{fn:{}});$.each=function(a,b){if(a instanceof
Array)a.forEach(function(a,c){b(c,a)});else for(var c in a)b(c,a[c])};$.isArray=function(a){return"array"===$.type(a)};$.noop=function(){};$.Deferred=function(){var a=new F;a.pipe=function(b,c){l(this,function(){b.apply(this,arguments)},function(){c.apply(this,arguments)});return a};var b=C.after(a,"cancel",function(){b.remove();a.abort&&a.abort.apply(a,arguments)});a.promise=function(){return this};a.done=function(a){l(this,function(b){a.apply(this,b)});return this};a.fail=function(a){l(this,function(){},
function(b){a.apply(this,b)});return this};a.always=function(a){l(this,function(){a.apply(this,arguments)},function(b){a.apply(this,arguments)});return this};a.resolveWith=function(a,b){return this.resolve.call(a,b)};var c=a.resolve;a.resolve=function(){var a=c.apply(this,arguments);a.__proto__.promise=function(){return this};return a};return a};$.isPlainObject=function(a){var b;if(!a||"object"!==typeof a||a.nodeType||null!=a&&a==a.window)return!1;try{if(a.constructor&&!hasOwn.call(a,"constructor")&&
!hasOwn.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(b in a);return void 0===b||hasOwn.call(a,b)};$.prop=function(a,b,c){return $(a).prop(b,c)};$.data=function(){var a=Array.prototype.slice.call(arguments),b=a.shift();return $(b).data.apply($(b),a)};$.type=function(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?x[toString.call(a)]||"object":typeof a};$.extend=function(){var a=Array.prototype.slice.call(arguments),b=a.shift();for("boolean"===typeof b&&
a.shift();0<a.length;)var c=a.shift(),b=f.mixin(b,c);return b};$.pushStack=function(a){a=jQuery.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;return a};$.inArray=function(a,b,c){return b?q.indexOf(b,a,c):-1};$.merge=function(a,b){for(var c=+b.length,d=0,e=a.length;d<c;)a[e++]=b[d++];if(c!==c)for(;void 0!==b[d];)a[e++]=b[d++];a.length=e;return a};$.makeArray=function(a,b){var c=b||[];if(null!=a){var d;d=a.length;var e=typeof a;d="function"===e||null!=a&&a==a.window?!1:1===a.nodeType&&
d?!0:"array"===e||0===d||"number"===typeof d&&0<d&&d-1 in a;d?$.merge(c,"string"===typeof a?[a]:a):[].push.call(c,a)}return c};$.expr={};$.expr[":"]={};$.support={};$.now=function(){return(new Date).getTime()};$.Event=function(a,b){if(!(this instanceof $.Event))return new $.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?m:n):this.type=a;b&&$.extend(this,b);this.timeStamp=a&&a.timeStamp||$.now()};
$.Event.prototype={isDefaultPrevented:n,isPropagationStopped:n,isImmediatePropagationStopped:n,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=m;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=m;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=m;a&&a.stopImmediatePropagation&&
a.stopImmediatePropagation();this.stopPropagation()}};$.ajaxSettings={xhr:function(){return new window.XMLHttpRequest},type:"GET",global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset\x3dUTF-8",accepts:{text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,
"text json":JSON.parse,"text xml":function(){}},flatOptions:{url:!0,context:!0}};$.isFunction=function(a){return"function"===$.type(a)};$.grep=function(a,b,c){for(var d=[],e=0,K=a.length,f=!c;e<K;e++)c=!b(a[e],e),c!==f&&d.push(a[e]);return d};$.ajax=function(a,b){"object"===typeof a&&(b=a,a=b.url);var c=b.type.toLowerCase()||"get",d={handleAs:b.dataType||"text",data:b.data},e=new $.Deferred;D[c](a,d).then(function(a){e.resolve([a,200,{}])},function(a){e.reject([a.response.xhr,a.response.status,a.response.xhr.responseText])});
return e};return $});
//# sourceMappingURL=$.js.map