//>>built
(function(c){"function"===typeof define&&define.amd?define("dexist/util/factory",["jquery"],c):c(jQuery)})(function(c){var n=0,m=Array.prototype.slice;c.cleanData=function(a){return function(b){var f,d,e;for(e=0;null!=(d=b[e]);e++)try{(f=c._data(d,"events"))&&f.remove&&c(d).triggerHandler("remove")}catch(g){}a(b)}}(c.cleanData);c.widget=function(a,b,f){var d,e,g,h,l={},k=a.split(".")[0];a=a.split(".")[1];d=k+"-"+a;f||(f=b,b=c.Widget);c.expr[":"][d.toLowerCase()]=function(a){return!!c.data(a,d)};c[k]=
c[k]||{};e=c[k][a];g=c[k][a]=function(a,b){if(!this._createWidget)return new g(a,b);arguments.length&&this._createWidget(a,b)};c.extend(g,e,{version:f.version,_proto:c.extend({},f),_childConstructors:[]});h=new b;h.options=c.widget.extend({},h.options);c.each(f,function(a,d){c.isFunction(d)?l[a]=function(){var c=function(){return b.prototype[a].apply(this,arguments)},f=function(c){return b.prototype[a].apply(this,c)};return function(){var a=this._super,b=this._superApply,e;this._super=c;this._superApply=
f;e=d.apply(this,arguments);this._super=a;this._superApply=b;return e}}():l[a]=d});g.prototype=c.widget.extend(h,{widgetEventPrefix:e?h.widgetEventPrefix||a:a},l,{constructor:g,namespace:k,widgetName:a,widgetFullName:d});e?(c.each(e._childConstructors,function(a,b){var d=b.prototype;c.widget(d.namespace+"."+d.widgetName,g,b._proto)}),delete e._childConstructors):b._childConstructors.push(g);c.widget.bridge(a,g);return g};c.widget.extend=function(a){for(var b=m.call(arguments,1),f=0,d=b.length,e,g;f<
d;f++)for(e in b[f])g=b[f][e],b[f].hasOwnProperty(e)&&void 0!==g&&(c.isPlainObject(g)?a[e]=c.isPlainObject(a[e])?c.widget.extend({},a[e],g):c.widget.extend({},g):a[e]=g);return a};c.widget.bridge=function(a,b){var f=b.prototype.widgetFullName||a;c.fn[a]=function(d){var e="string"===typeof d,g=m.call(arguments,1),h=this;d=!e&&g.length?c.widget.extend.apply(null,[d].concat(g)):d;e?this.each(function(){var b,e=c.data(this,f);if("instance"===d)return h=e,!1;if(!e)return c.error("cannot call methods on "+
a+" prior to initialization; attempted to call method '"+d+"'");if(!c.isFunction(e[d])||"_"===d.charAt(0))return c.error("no such method '"+d+"' for "+a+" widget instance");b=e[d].apply(e,g);if(b!==e&&void 0!==b)return h=b&&b.jquery?h.pushStack(b.get()):b,!1}):this.each(function(){var a=c.data(this,f);a?(a.option(d||{}),a._init&&a._init()):c.data(this,f,new b(d,this))});return h}};c.Widget=function(){};c.Widget._childConstructors=[];c.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"\x3cdiv\x3e",
options:{disabled:!1,create:null},_createWidget:function(a,b){b=c(b||this.defaultElement||this)[0];this.element=c(b);this.uuid=n++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=c.widget.extend({},this.options,this._getCreateOptions(),a);this.bindings=c();this.hoverable=c();this.focusable=c();b!==this&&(c.data(b,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===b&&this.destroy()}}),this.document=c(b.style?b.ownerDocument:b.document||b),this.window=c(this.document[0].defaultView||
this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:c.noop,_getCreateEventData:c.noop,_create:c.noop,_init:c.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetFullName).removeData(c.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);
this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:c.noop,widget:function(){return this.element},option:function(a,b){var f=a,d,e,g;if(0===arguments.length)return c.widget.extend({},this.options);if("string"===typeof a)if(f={},d=a.split("."),a=d.shift(),d.length){e=f[a]=c.widget.extend({},this.options[a]);for(g=0;g<d.length-1;g++)e[d[g]]=e[d[g]]||{},e=e[d[g]];a=d.pop();if(1===arguments.length)return void 0===e[a]?null:e[a];e[a]=b}else{if(1===arguments.length)return void 0===
this.options[a]?null:this.options[a];f[a]=b}this._setOptions(f);return this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,b){this.options[a]=b;"disabled"===a&&(this.widget().toggleClass(this.widgetFullName+"-disabled",!!b),b&&(this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus")));return this},enable:function(){return this._setOptions({disabled:!1})},disable:function(){return this._setOptions({disabled:!0})},
_on:function(a,b,f){var d,e=this;"boolean"!==typeof a&&(f=b,b=a,a=!1);f?(b=d=c(b),this.bindings=this.bindings.add(b)):(f=b,b=this.element,d=this.widget());c.each(f,function(f,h){function l(){if(a||!(!0===e.options.disabled||c(this).hasClass("ui-state-disabled")))return("string"===typeof h?e[h]:h).apply(e,arguments)}"string"!==typeof h&&(l.guid=h.guid=h.guid||l.guid||c.guid++);var k=f.match(/^([\w:-]*)\s*(.*)$/),m=k[1]+e.eventNamespace;(k=k[2])?d.delegate(k,m,l):b.bind(m,l)})},_off:function(a,b){b=
(b||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;a.unbind(b).undelegate(b)},_delay:function(a,b){var c=this;return setTimeout(function(){return("string"===typeof a?c[a]:a).apply(c,arguments)},b||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){c(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){c(a.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,
{focusin:function(a){c(a.currentTarget).addClass("ui-state-focus")},focusout:function(a){c(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(a,b,f){var d,e=this.options[a];f=f||{};b=c.Event(b);b.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();b.target=this.element[0];if(a=b.originalEvent)for(d in a)d in b||(b[d]=a[d]);this.element.trigger(b,f);return!(c.isFunction(e)&&!1===e.apply(this.element[0],[b].concat(f))||b.isDefaultPrevented())}};c.each({show:"fadeIn",
hide:"fadeOut"},function(a,b){c.Widget.prototype["_"+a]=function(f,d,e){"string"===typeof d&&(d={effect:d});var g,h=!d?a:!0===d||"number"===typeof d?b:d.effect||b;d=d||{};"number"===typeof d&&(d={duration:d});g=!c.isEmptyObject(d);d.complete=e;d.delay&&f.delay(d.delay);if(g&&c.effects&&c.effects.effect[h])f[a](d);else if(h!==a&&f[h])f[h](d.duration,d.easing,e);else f.queue(function(b){c(this)[a]();e&&e.call(f[0]);b()})}})});
//# sourceMappingURL=factory.js.map