//>>built
define("xstyle/core/parser",["xstyle/core/utils"],function(P){function J(){this.push.apply(this,arguments)}function K(f){this.value=f}function L(f,s,D){function E(t,r){function s(a){y=!1;var k=n.lastIndex;a.then(function(){y=!0;e&&(n.lastIndex=k,x())});var e=!0}function x(){function f(a){a&&("string"==typeof a&&x)&&(a=x+a);b?b.push?"string"==typeof b[b.length-1]&&"string"==typeof a?b[b.length-1]+=a:a&&b.push(a):"string"==typeof b&&"string"==typeof a?b+=a:b=new J(b,a):b=a}for(y=!0;y;){var q=n.exec(t);
if(!q)break;var e=q[5],x=q[1],c=q[2],l=q[3],g=q[4],h,m,b,F,g=g&&G(g),c=c&&G(c);u?(l?(m=c,h=l.charAt(0),F="?"==l.charAt(1),-1<l.indexOf("\n")&&(g=l.slice(1))):g=c,b=g,u=!1):(g=l?c+l:c,f(g));"{"!=e&&(k+=q[0]);switch(e){case "'":case '"':var z="'"==e?Q:R;z.lastIndex=n.lastIndex;e=z.exec(t);c=e[1];n.lastIndex=z.lastIndex;f(new K(c));k+=e[0];continue;case "\\":e=z.lastIndex++;f(t.charAt(e));continue;case "(":case "{":case "[":var d,M=!1;if("{"==e){u=!0;":"==h&&l&&(c+=l);k=G((k+c).replace(/\s+/g," ").replace(/([\.#:])\S+|\w+/g,
function(a,b){return b?a:a.toLowerCase()}));f(d=a.newRule(k));"\x3d"==h&&(A=!1,b.creating=!0,g&&(M=!0));":"==h&&!a.root&&(b.creating=!0);var v=null,I=B;if(q[6]&&(l=r.cssRules||r.rules,d.cssRule=v=l[q[6].slice(1)]))k=v.selectorText;if(a.root&&A)for(l=r.cssRules||r.rules;v=l[B++];)if(v.selectorText==k){d.cssRule=v;break}v||(d.ruleIndex=B=I,d.styleSheet=r);b.creating?(d.selector="."+("\x3d"==h?c.match(/[\w-]*$/g,"")[0]:"")+"-x-"+S++,d.creating=!0):d.selector=a.root?k:a.selector+" "+k;k=""}else c=g.match(/(.*?)([\w-]*)$/),
f(d=a.newCall(c[2],b,a)),d.ref=a.getDefinition(c[2]),(b.calls||(b.calls=[])).push(d);d.parent=a;M&&g.replace(/(?:^|\s+)([\w-]+)\s*$/g,function(a,b){var c=P.extend(d,b,D);c&&c.then&&s(c)});a.currentName=m;a.currentSequence=b;a.assignmentOperator=h;var C;if("{"==e&&(C=d.selector.match(/[@:]\w+/)))C=C[0],(m=a.getDefinition(C))&&m.selector&&m.selector(d);p.push(a=d);a.operator=e;a.start=n.lastIndex;b=m=null;continue}if(b)if(c="string"==typeof b?b:b[0],c.charAt&&"@"==c.charAt(0))if(g=c.match(/\w+/)[0],
"import"==g)c=L.getStyleSheet((r.cssRules||r.imports)[B++],b,r),g=n.lastIndex,E(c.localSource,c),n.lastIndex=g;else{if("xstyle"==g){if("start"==c.slice(8,13))d=a?a.newRule(""):N,d.root=a.root,d.parent=a,p.push(a=d);else{var N=a||N;p.pop();a=p[p.length-1]}n=a?O:/(@[\w\s])/g}}else if(h)try{var w=a[":"==h?"setValue":"declareProperty"](m,b,F);w&&w.then&&s(w)}catch(T){}switch(e){case ":":"\x3d"==h?(u=!0,h=":"):f(":");break;case "}":case ")":case "]":m=null;m=t.slice(a.start,n.lastIndex-1);a.cssText=a.cssText?
a.cssText+";"+m:m;if("}"==e){"}"==H&&(H=a.parent.selector)&&H.charAt(0);if(!a.root){try{a.onRule(a.selector,a)}catch(U){}A=!0}k=""}")"==e&&!h&&(a.args=b.isSequence?b:[b],(w=p[p.length-2].onCall(a))&&w.then&&s(w));p.pop();a=p[p.length-1];b=a.currentSequence;m=a.currentName;h=a.assignmentOperator;if(a.root&&"}"==e){if(h)try{a[":"==h?"setValue":"declareProperty"](m,b[1]||b,F)}catch(V){}u=!0;h=!1}break;case "":case void 0:return;case ";":b=null,u=!0,h=A=!1,k=""}var H=e}}function D(a){}t=t.replace(I,function(a){return a.replace(/[^\n]/g,
"")});var a=f;n.lastIndex=0;var y,B=0,A=!0,k="",u=!0;x()}var O,n=O=/(\s*)((?:[^{\}\[\]\(\)\\'":=;]|\[(?:[^\]'"]|'(?:\\.|[^'])*'|"(?:\\.|[^"])*")\])*)([=:]\??\s*([^{\}\[\]\(\)\\'":;]*))?(?:([{\}\[\]\(\)\\'":;])(\/\d+)?|$)/g,p=[f];f.parse=E;E(s,D)}var Q=/((?:\\.|[^'])*)'/g,R=/((?:\\.|[^"])*)"/g,I=/\/\*[\w\W]*?\*\//g,S=0,G="".trim?function(f){return f.trim()}:function(f){return f.replace(/^\s+|\s+$/g,"")},s=J.prototype=[];s.toString=function(){return this.join("")};s.isSequence=!0;K.prototype.toString=
function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};return L});
//# sourceMappingURL=parser.js.map