//>>built
define("dforma/Builder","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/aspect dojo/Deferred dojo/when dojo/promise/all dojo/keys dojo/number dojo/dom-construct dojo/dom-class dojo/store/Memory ./_GroupMixin ./Group ./Label ./jsonschema dforma/util/i18n dijit/Dialog dijit/form/Form dijit/form/_FormValueWidget dijit/form/Button dijit/form/FilteringSelect dijit/form/ComboBox dijit/form/TextBox dforma/util/string/toProperCase dforma/validate/web dforma/validate/us dojo/i18n!./nls/common".split(" "),
function(F,G,k,s,w,v,H,T,I,J,U,f,B,K,V,C,L,M,N,O,W,q,P,Q,R,X){var x=M.load("dforma","common"),z=G("dforma.Builder",[K,O],{baseClass:"dformaBuilder",templateString:'\x3cdiv aria-labelledby\x3d"${id}_label"\x3e\x3cdiv class\x3d"dijitReset dijitHidden ${baseClass}Label" data-dojo-attach-point\x3d"labelNode" id\x3d"${id}_label"\x3e\x3c/div\x3e\x3cform class\x3d"dformaBuilderForm" data-dojo-attach-point\x3d\'containerNode\' data-dojo-attach-event\x3d\'onreset:_onReset,onsubmit:_onSubmit\' ${!nameAttrSetting}\x3e\x3c/form\x3e\x3cdiv class\x3d"dijitReset dijitHidden ${baseClass}Hint" data-dojo-attach-point\x3d"hintNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"dijitReset dijitHidden ${baseClass}Message" data-dojo-attach-point\x3d"messageNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"dijitReset ${baseClass}ButtonNode" data-dojo-attach-point\x3d"buttonNode"\x3e\x3c/div\x3e\x3c/div\x3e',
controller:null,controllerWidget:null,data:null,store:null,cancellable:!1,submittable:!0,hideOptional:!1,allowFreeKey:!1,allowOptionalDeletion:!1,editControls:null,submit:function(){},cancel:function(){},onSubmit:function(h){this.submit();return!1},focus:function(){},_removeProperty:function(h,f){var m=f.item,k=m.properties;delete k[h.name];return this.store?this.store.put({id:m.id,properties:k},{incremental:!0}):(new v).resolve()},_addEditForm:function(h,f){var m=this,q=f.item,n=q.properties,p=q.id,
r=[],e;for(e in n)if(h.name==e)return s.forEach(h.editControls,function(g,f){if("checkbox"==g.type)r.push(g.name),h.editControls[f].checked=n[e][g.name];else if("multiselect_freekey"==g.type){var k=[];s.forEach(n[e][g.name],function(a){k.push({value:a,label:a,selected:!0})});h.editControls[f].options=k}else h.editControls[f].value=n[e][g.name]}),new z({style:"height:100%;border:1px solid gray",cancel:function(){m.rebuild()},cancellable:!0,submit:function(){if(this.validate()){var g=this.get("value"),
e;for(e in g)k.isArray(g[e])?-1<s.indexOf(r,e)&&(s.forEach(g[e],function(f,a){g[e][a]="on"==f}),0===g[e].length?g[e]=!1:2>g[e].length&&(g[e]=g[e][0])):g[e]||delete g[e];n[h.name]=g;h.add&&(delete h.add,f.item.controls.push(k.mixin(h,g)));m.store&&H(m.store.put({id:p,properties:n},{incremental:!0}),function(e){},function(e){if(m.store.onError)m.store.onError(e,"put",{id:p,properties:n},{incremental:!0})});m.rebuild()}},data:{controls:h.editControls,cancel:{label:x.buttonCancel},submit:{label:x.buttonSave}}})},
rebuild:function(h){function D(){g.sort(function(a,c){return a.name<c.name?-1:a.name>c.name?1:0})}function m(a){var c=a.map(function(a){var b;switch(a.type){case "date":b="dijit/form/DateTextBox";break;case "repeat":b="dforma/Repeat";break;case "lookuplist":b="dforma/LookupList";break;case "checkbox":b="dijit/form/CheckBox";break;case "radiogroup":b="dforma/RadioGroup";break;case "select":b="dijit/form/FilteringSelect";break;case "textarea":b="dijit/form/Textarea";break;case "spinner":b="dijit/form/NumberSpinner";
break;case "number":b="dijit/form/NumberTextBox";break;case "currency":b="dijit/form/CurrencyTextBox";break;case "combo":b="dijit/form/ComboBox";break;case "grid":b="dforma/Grid";break;case "multiselect":case "multiselect_freekey":b="dforma/MultiSelect";break;case "hslider":b="dijit/form/HorizontalSlider";break;case "vslider":b="dijit/form/VerticalSlider";break;case "colorpicker":b="dforma/ColorPickerBox";break;case "color":b="dforma/ColorPaletteBox";break;case "colorpalette":b="dlagua/w/ColorPalette";
break;case "group":b=a.hidden?"dforma/HiddenGroup":"dforma/Group";break;case "unhidebutton":b="dijit/form/ToggleButton";break;case "switch":break;default:b=a.required||"email"==a.type||"phone"==a.type||a.readonly?"dijit/form/ValidationTextBox":"dijit/form/TextBox"}return b}),b=new v;F(c,function(){var c=arguments;a.forEach(function(a,b){a.Widget=c[b]});b.resolve()});return b}function y(a,c){c||(c=e);var b,l,u=a.Widget;delete a.Widget;var h=a.title?a.title:a.name.toProperCase(),d=k.mixin({placeHolder:h,
label:h,"class":"dforma"+a.type.toProperCase()+" dforma"+a.type.toProperCase()+"-"+a.name,onChange:function(a){"checkbox"==this.type&&(a=this.value=!0===this.checked);this._config.value=a;this.controller&&this._form.rebuild()}},a);a.hasOwnProperty("readonly")&&(d.readOnly=a.readonly);switch(a.type){case "checkbox":d.checked=!0===a.value;d.validate=function(){return this.hasOwnProperty("isValid")&&this.checked!=this.isValid?(alert(this.invalidMessage),!1):!0};break;case "radiogroup":d.labelAttr="title";
break;case "currency":d.value=parseInt(a.value,10);break;case "date":d.constraints={selector:"date"};break;case "repeat":d.cols=a.options[0].controls.length;d.item=a.options[0];d.hint=a.description||"";break;case "textarea":d.block=!0;break;case "grid":d.hint=a.description||"";if(a.columns)for(var n in a.columns)"currency"==a.columns[n].format&&(d.columns[n].get=function(a){return J.format(a[n],{places:2})});d.store||(d.store=c.store);d.subform=new z({cancellable:!0,cancel:function(){f.toggle(this.parentform.domNode,
"dijitHidden",!1);f.toggle(c.buttonNode,"dijitHidden",!1);f.toggle(c.hintNode,"dijitHidden",!1);f.toggle(this.domNode,"dijitHidden",!0);c.layout();this.data&&(this.data.id&&this.parentform.newdata)&&this.parentform.store.remove(this.data.id);this.data=null;this.parentform.newdata=!1},submit:function(){if(this.validate()){f.toggle(this.parentform.domNode,"dijitHidden",!1);f.toggle(c.buttonNode,"dijitHidden",!1);f.toggle(c.hintNode,"dijitHidden",!1);f.toggle(this.domNode,"dijitHidden",!0);c.layout();
var a=this.get("value");this.parentform.save(a,{id:this.data.id,overwrite:!0})}}});var v=k.hitch(d.subform,d.subform.validate);d.subform.validate=function(){return!this.data?!0:v()};c.own(w.after(d.subform,"layout",function(){c.layout()}),w.after(c,"cancel",function(){d.subform.cancel()}));var S=w.after(c,"layout",function(){S.remove();if(b.store&&b.store.selectedId){var a=b.store.selectedId;b.newdata=b.store.newdata;delete b.store.newdata;b.store.selectedId=null;b.onEdit&&b.onEdit(a)}});d.onEdit=
function(b,d){d=d||{};var e=this.store.get(b);f.toggle(this.domNode,"dijitHidden",!0);f.toggle(c.buttonNode,"dijitHidden",!0);f.toggle(c.hintNode,"dijitHidden",!0);f.toggle(this.subform.domNode,"dijitHidden",!1);this.subform.rebuild({id:b,options:d,controls:[L.schemasToController(a.schema.items,e,{selectFirst:!0,controller:{name:a.controller.name,type:a.controller.type,title:a.controller.title}})],submit:{label:x.buttonSave}})};break;case "group":d.item=a.options[0];d.hint=a.description||"";break;
case "email":d.validator=dforma.validate.isEmailAddress;break;case "phone":d.validator=dforma.validate.us.isPhoneNumber;break;case "unhidebutton":h=d.label.split("|");d.label=h[0];d.splitLabel=h;d.onClick=function(){f.toggle(this.getParent().containerNode,"dijitHidden",!this.checked);this.value=this.checked?"on":"";this.set("label",this.splitLabel[this.checked?1:0])};break;case "select":case "combo":d=k.mixin({store:new B({data:a.options}),searchAttr:a.searchAttr||"id",autoComplete:!0},d)}a.controller&&
(d._form=c);d._config=a;b=new u(d);a.controller&&(r=c.controllerWidget=b);if("grid"==a.type)c.addChild(b),d.subform.parentform=b,c.addChild(d.subform);else if("repeat"==a.type||"group"==a.type)c.addChild(b),s.forEach(a.options,function(a){a.controls&&m(a.controls).then(function(){s.forEach(a.controls,function(a){y(a,b)})})}),b.set("value",a.value);else if("repeat"==c.type)c.addControl(u,d);else if("hidden"==a.type||a.hidden)c.addChild(b),f.toggle(b.domNode,"dijitHidden",!0);else if("unhidebutton"==
a.type){var A;if(a.target){for(u=0;u<p.length;u++)if(p[u].name==a.target){A=p[u].widget;break}A&&(b.addChild(A),c.addChild(b))}else b.placeAt(c.buttonNode)}else{l=new C({label:d.label,"class":"dformaLabelFor"+a.type.toProperCase(),child:b,title:a.description?a.description:d.label});if("checkbox"==a.type)l.on("click",function(a){"INPUT"!=a.target.nodeName&&b.set("checked",!b.checked)});a.dialog&&(new q({label:a.dialog,"class":"dformaPopupTrigger",onClick:function(){(new N({content:a.description})).show()}})).placeAt(l["labelNode_"+
l.position],"before");c.addChild(l);"multiselect_freekey"==a.type&&(l.child=null,l.addChild(b),l.addChild(new R({onChange:function(a){a&&b.addOption({value:a,label:a,selected:!0});this.set("value","")},onBlur:function(){this.onChange(this.value)},onKeyPress:function(a){a.charOrCode==I.ENTER&&this.focusNode.blur()}})))}if(!0===a.edit||!0===a["delete"])if(l||(l=new C({label:d.label,"class":"dformaLabelFor"+a.type.toProperCase(),child:b,title:a.description?a.description:d.label}),c.addChild(l)),!0===
a.edit&&(b.editButton=new q({label:"Edit",target:{control:a,widget:b,label:l},controller:r,showLabel:!1,iconClass:"dijitEditorIcon dformaEditIcon",onClick:function(){function a(){d&&d.remove();c&&c.remove();this.target.widget.editButton.destroyRecursive();this.target.widget.deleteButton&&this.target.widget.deleteButton.destroyRecursive();this.target.control.add&&t&&(g.length||e.allowFreeKey?t.set("disabled",!1):t.destroyRecursive())}var b=e._addEditForm(this.target.control,this.controller);this.target.label.addChild(b);
var d,c;d=w.after(b,"submit",k.hitch(this,a));c=w.after(b,"cancel",k.hitch(this,a))}}),l.addChild(b.editButton)),a["delete"]&&(b.deleteButton=new q({label:"Delete",showLabel:!1,target:{control:a,widget:b,label:l},iconClass:"dijitEditorIcon dformaDeleteIcon",onClick:function(){this.target.widget.set("value",null);this.target.label.destroyRecursive();var a=this.target.control;a.edit||a["delete"]&&!e.allowOptionalDeletion?e._removeProperty(a,r):p.forEach(function(b,d){a.name===b.name&&(g.push(a),D())})}}),
l.addChild(b.deleteButton)),a.edit&&a.add)b.editButton.onClick();return b}var n=new v;h?this.data=h:h=this.data;this.destroyDescendants();var p=this.data.controls,r,e=this;s.forEach(p,function(a){a.controller&&("repeat"!=a.type&&"group"!=a.type)&&(e.controller=a,s.forEach(a.options,function(c){c.id==a.value&&c.controls&&(p=p.concat(c.controls))}))});var g=[],E=this.hideOptional,t,p=s.map(p,function(a,c){a.required||!E||a.hasOwnProperty("value")||a.hasOwnProperty("checked")?!a.required&&e.allowOptionalDeletion&&
(a["delete"]=!0):(a["delete"]=!0,g.push(a));return a},this);D();m(p).then(k.hitch(this,function(){var a={};p.forEach(function(b,c){if(-1==g.indexOf(b)){var e=y(b);e&&(a[b.name]=e)}});this.layout&&this.layout();if(E&&g.length||this.allowFreeKey){var c=function(a){var c={store:new B({data:a}),searchAttr:"name",labelType:"html",labelFunc:function(a,b){var d=a.name;a.description&&(d='\x3cdiv title\x3d"'+a.description+'"\x3e'+d+"\x3c/div\x3e");return d},onChange:function(c){var g=-1;s.forEach(a,function(a,
b){a.name==c&&(g=b)});if(-1<g){var d=a.splice(g,1);m(d).then(function(){y(d[0]).focus()})}else if(e.allowFreeKey){var f={type:"input",name:c,placeHolder:c.toProperCase(),label:c.toProperCase()};if(e.editControls||r.editControls)f["delete"]=f.edit=f.add=!0,f.editControls=e.editControls||r.editControls,r.item.properties||(r.item.properties={}),r.item.properties[c]={};m([f]).then(function(){y(f)})}this.destroyRecursive();t.set("disabled",!1);e.addChild(t)}},c=e.allowFreeKey?new Q(c):new P(c);e.addChild(c)};
t=new q({label:"Add optional property",showLabel:!1,iconClass:"dijitEditorIcon dformaAddIcon",onClick:function(){this.set("disabled",!0);c(g)}});e.addChild(t)}n.resolve(a)}));this.submitButton&&this.submitButton.destroy();this.cancelButton&&this.cancelButton.destroy();this.submittable&&(this.submitButton=(new q(k.mixin({label:x.buttonSubmit,"class":"dformaSubmit",onClick:k.hitch(this,this.submit)},this.data.submit))).placeAt(this.buttonNode));this.cancellable&&(this.cancelButton=(new q(k.mixin({label:x.buttonCancel,
"class":"dformaCancel",onClick:k.hitch(this,this.cancel)},this.data.cancel))).placeAt(this.buttonNode));return n},startup:function(){if(!this._started)return this.submitButton=new q,this.cancellable&&(this.cancelButton=new q),this.inherited(arguments),this.data?this.rebuild():(new v).resolve()}});return z});
//# sourceMappingURL=Builder.js.map