//>>built
define("dexist/CollectionBrowser","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-geometry dojo/dom-form dojo/on dojo/query dojo/request dojo/data/ObjectStore dstore/Memory dstore/Cache dstore/Rest dijit/registry dijit/layout/ContentPane dijit/layout/LayoutContainer dijit/layout/StackContainer dijit/Toolbar dijit/Dialog dijit/form/Button dijit/form/CheckBox dijit/form/Select dgrid/OnDemandGrid dgrid/Editor dgrid/Keyboard dgrid/Selection dgrid/extensions/DijitRegistry dforma/Builder dojo/_base/sniff".split(" "),
function(p,d,m,r,s,g,H,I,t,f,u,v,J,K,L,w,x,q,y,z,A,n,l,M,N,B,C,D,E,F,G){var e={confirm:function(b,a,c){var h=new n({title:b});b=g.create("div",{style:"width: 400px;"},h.containerNode,"last");a=g.create("p",{innerHTML:a});b.appendChild(a);a=new l({label:"Yes"});f(a,"click",d.hitch(this,function(){h.hide();c()}));b.appendChild(a.domNode);a=new l({label:"No"});f(a,"click",d.hitch(this,function(){h.hide()}));b.appendChild(a.domNode);h.show()},message:function(b,a,c,h){if(!c||"function"==typeof c)h=c,
c="Close";var d=new n({title:b});f(d,"hide",function(a){d.destroyRecursive();h&&h()});b=g.create("div",{style:"width: 400px;"},d.containerNode,"last");a=g.create("div",{innerHTML:a});b.appendChild(a);c=new l({label:c,onClick:function(){d.hide()}});b.appendChild(c.domNode);d.show()},input:function(b,a,c,d){var e=new n({title:b});b=g.create("div",{style:"width: 400px;"},e.containerNode,"last");a=g.create("p",{innerHTML:a});b.appendChild(a);var f=g.create("form",{innerHTML:c},b,"last");c=new l({label:"Cancel",
onClick:function(){e.hide();e.destroyRecursive()}});b.appendChild(c.domNode);c=new l({label:"Ok",onClick:function(){e.hide();e.destroyRecursive();var a=t.toObject(f);d(a)}});b.appendChild(c.domNode);e.show()}},k;return p("dexist.CollectionBrowser",[z],{store:null,grid:null,target:"db/",collection:"/db",clipboard:null,clipboardCut:!1,editor:null,tools:null,baseClass:"dexistCollectionBrowser",updateBreadcrumb:function(){var b=this;this.breadcrumb.innerHTML="";m.forEach(this.collection.split("/"),function(a,
c,d){a&&g.create("a",{innerHTML:a,target:d.slice(0,c+1).join("/"),onclick:function(){b.refresh(this.target)}},this.breadcrumb)},this)},startup:function(){if(!this._started){var b=this;this.loadCSS(require.toUrl("dexist/resources/CollectionBrowser.css"));this.browsingPage=new y({});this.propertiesPage=new q({});this.browsingTop=new q({region:"top"});this.browsingPage.addChild(this.browsingTop);this.toolbar=new A;this.browsingTop.addChild(this.toolbar);this.breadcrumb=g.create("div",{"class":"dexistBreadCrumb"},
this.browsingTop.domNode,"last");this.updateBreadcrumb();this.store=new w({useRangeHeaders:!0,target:this.target,rpc:function(a,b,d,e){return v.post(this.target+a,{data:JSON.stringify({method:b,params:d,id:e||"call-id"}),handleAs:"json",headers:{"Content-Type":"application/json",Accept:"application/json"}})}});this.grid=new (p([B,D,E,C,F]))({region:"center",id:"browsingGrid",collection:this.store.filter({collection:this.collection}),columns:[{label:"Name",field:"name",editor:"text",editOn:"click",
canEdit:function(a,b){return".."!=b}},{label:"Permissions",field:"permissionsString"},{label:"Owner",field:"owner"},{label:"Group",field:"group"},{label:"Last-modified",field:"lastModified"}]});this.browsingPage.addChild(this.grid);this.grid.on("dgrid-refresh-complete",d.hitch(this,function(){this.resize();var a=dijit.getEnclosingWidget(this.domNode.parentNode);a&&a.resize()}));this.grid.on(".dgrid-row:dblclick",d.hitch(this,function(a){var b=this.grid.row(a).data;if(b.isCollection)this.collection=
"/db/"+b.id,this.updateBreadcrumb(),this.grid.set("collection",this.store.filter({collection:this.collection}));else if(a.altKey)this.openResource(b.id);else this.onSelectResource(b.id,b)}));this.grid.on("dgrid-select",function(a){k=m.map(a.rows,function(a){return a.data})});this.tools={};m.forEach([{id:"reload",title:"Refresh"},{id:"reindex",title:"Reindex collection"},{id:"new",title:"New collection"},{id:"delete",title:"Delete resources"},{id:"properties",title:"Edit owner, groups and permissions"},
{id:"copy",title:"Copy selected resources"},{id:"cut",title:"Cut selected resources"},{id:"paste",title:"Paste resources"},{id:"add",title:"Upload resources"}],function(a){var b=new l({title:a.title,iconClass:"dexistToolbar-"+a.id,showLabel:!1});this.tools[a.id]=b;this.toolbar.addChild(b)},this);this.tools.properties.on("click",d.hitch(this,function(a){k.length&&0<k.length&&this.store.get(k[0].id).then(d.hitch(this,function(a){this.selectChild(this.propertiesPage);this.form.rebuild({controls:[{name:"name",
title:"Resource",type:"text",readOnly:!0},{name:"internetMediaType",title:"Internet Media Type",type:"text",readOnly:!0},{name:"created",type:"text",readOnly:!0},{name:"lastModified",title:"Last Modified",type:"text",readOnly:!0},{name:"owner",type:"text",trim:!0},{name:"group",type:"text",trim:!0},{name:"permissions",type:"grid",add:!1,edit:!1,remove:!1,style:"height:200px",selectionMode:"none",columns:[{label:"Permission",field:"id"},{label:"Read",field:"read",editor:"checkbox"},{label:"Write",
field:"write",editor:"checkbox"},{label:"Execute",field:"execute",editor:"checkbox"},{label:"Special",field:"special",editor:"checkbox"}]},{name:"acl",type:"grid",style:"height:200px",columns:[{label:"Target",field:"target",width:"20%"},{label:"Subject",field:"who",width:"30%"},{label:"Access",field:"access",width:"20%"},{label:"Read",field:"read",width:"10%",editor:"checkbox"},{label:"Write",field:"write",width:"10%",editor:"checkbox"},{label:"Execute",field:"execute",width:"10%",editor:"checkbox"}]}]}).then(d.hitch(this,
function(b){this.form.set("value",a)}))}))}));f(this.tools["delete"],"click",d.hitch(this,"deleteResources"));f(this.tools["new"],"click",d.hitch(this,"createCollection"));f(this.tools.add,"click",d.hitch(this,"upload"));f(this.tools.copy,"click",function(a){a.preventDefault();b.clipboard=b.getSelected();b.clipboardCut=!1});f(this.tools.cut,"click",function(a){a.preventDefault();b.clipboard=b.getSelected();b.clipboardCut=!0});f(this.tools.paste,"click",d.hitch(this,"pasteResources"));f(this.tools.reload,
"click",d.hitch(this,"refresh"));f(this.tools.reindex,"click",d.hitch(this,"reindex"));this.addChild(this.browsingPage);this.addChild(this.propertiesPage);this.grid.startup();this.form=new G({cancellable:!0,cancel:function(){b.selectChild(b.browsingPage)},submit:function(){if(this.validate()){var a=this.get("value");b.store.put(a).then(function(){b.selectChild(b.browsingPage);e.message("Properties updated successfully","Properties updated")},function(a){e.message("Changing Properties Failed!","Could not change properties on all resources! \x3cbr\x3eServer says: "+
a.response.xhr.responseText)})}}});this.propertiesPage.addChild(this.form);this.grid.focus();this.inherited(arguments)}},getSelected:function(b){if(k.length&&0<k.length){var a=[];m.forEach(k,function(c){(!b||c.isCollection)&&a.push(c.id)});return a}return null},refresh:function(b){b&&(this.collection=b,this.updateBreadcrumb());this.grid.set("collection",this.store.filter({collection:this.collection}))},changeCollection:function(b){b=this.grid.getItem(b);b.isCollection&&(this.collection=b.id,this.grid.selection.deselectAll(),
this.grid.set("collection",this.store.filter({collection:this.collection})),this.grid.focus.setFocusIndex(0,0))},createCollection:function(){var b=this;e.input("Create Collection","Create a new collection","\x3clabel for\x3d'name'\x3eName:\x3c/label\x3e\x3cinput type\x3d'text' name\x3d'name'/\x3e",function(a){var c=b.collection.replace(/^\/db\/?/,"");b.store.rpc(c,"create-collection",[a.name]).then(function(){b.refresh()},function(b){e.message("Creating Collection Failed!","Could not create collection \x26apos;"+
a.name+"\x26apos;.\x3cbr\x3eServer says: "+b.response.xhr.responseText)})})},deleteResources:function(b){b.preventDefault();var a=this,c=a.getSelected();c&&e.confirm("Delete Resources?","Are you sure you want to delete the selected resources?",function(){a.store.rpc("","delete-resources",[c]).then(function(){a.refresh()},function(a){e.message("Deletion Failed!","Resources could not be deleted.\x3cbr\x3eServer says: "+a.response.xhr.responseText)})})},pasteResources:function(b){b.preventDefault();
this.clipboard&&0<this.clipboard.length&&(b=this.collection.replace(/^\/db\/?/,""),this.store.rpc(b,this.clipboardCut?"move-resources":"copy-resources",[this.clipboard]).then(d.hitch(this,function(){this.clipboard=null;this.clipboardCut=!1;this.refresh()}),d.hitch(this,function(a){this.clipboard=null;this.clipboardCut=!1;e.message("Paste Failed!","Some resources could not be copied.")})))},upload:function(){s.byId("browsing-upload-collection").value=this.collection;x.byId("browsing-upload-dialog").show()},
reindex:function(){var b=this,a=this.collection.replace(/^\/db\/?/,""),c=this.getSelected(!0);if(c&&0<c.length){if(1<c.length){e.message("Reindex","Please select a single collection or none to reindex the current root collection");return}a=c[0]}e.confirm("Reindex collection?","Are you sure you want to reindex collection "+a+"?",function(){b.store.rpc(a,"reindex").then(function(){b.refresh()},function(){e.message("Reindex Failed!","Reindex of collection "+a+" failed");b.refresh()})})},onSelectResource:function(b){},
openResource:function(b){var a=window.open("","eXide");if(a&&!a.closed)if(a.eXide)a.eXide.app.findDocument(b),a.focus(),setTimeout(function(){(r("ie")||"function"==typeof a.eXide.app.hasFocus&&!a.eXide.app.hasFocus())&&e.message("Open Resource","Opened code in existing eXide window.")},200);else{window.eXide_onload=function(){a.eXide.app.findDocument(b)};var c=window.location.href,c=c.substring(0,c.indexOf("/dashboard"))+"/eXide/index.html";a.location=c}else e.message("Open Resource","Failed to start eXide in new window.")},
loadCSS:function(b){var a=document.getElementsByTagName("head")[0];u("link",a).forEach(function(a){a.getAttribute("href")});var c=document.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("href",b);a.appendChild(c)}})});
//# sourceMappingURL=CollectionBrowser.js.map